config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :articles
  get '/articles' => 'articles#index'
  get '/articles/new' => 'articles#new', as: 'new_article'
  post '/articles' => 'articles#create', as: 'create_article'
  get '/articles/:id/edit' => 'articles#edit', as: 'edit_article'
  patch 'articles/:id' => 'articles#update', as: 'update_article'
  get 'articles/:id/show' => 'articles#show', as: 'show_article'
  get 'articles/:id' => 'articles#delete', as: 'delete_article'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :name, presence: true,
                     uniqueness: true
    validates :body, presence: true,
                     length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        # Article.new is a model
        # render forms
        @article = Article.new
    end

    def create
        # tatanggapin kung ano yung sinubmit ng user natin
        @article = Article.new(article_params)
        # @article.name = params[:article][:name]
        # @article.body = params[:article][:body]
        if @article.save
            redirect_to articles_path
        else
            render :new
        end
    end

    def edit
        # @article = Article.find(id)
        # @article.name = params[:article][:name]
        # @article.body = params[:article][:body]
        # @article.save
        @article = Article.find(params[:id])
        
    end

    def update
        @article = Article.find(params[:id])
        
         if @article.update(article_params)
             redirect_to articles_path
         else
             render :edit
         end
    end

    def delete
        # @article = Article. #parameter you want to delete
        # @article.destroy
        @article = Article.find(params[:id]).destroy
        redirect_to articles_path
    end

    private
    def article_params
        params.require(:article).permit(:name, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h1>Edit Page</h1>
<%= form_with scope: :article, url: update_article_path, method: :patch do |f| %>
<p>
    <% if @article.errors.any? %>
        <ul>
            <% @article.errors.full_messages.each do |message| %>
             <li>
                <%= message%>
             </li>
            <% end %>
        </ul>
    <% end %>
</p>

<p>
    <%= f.label :name %>
    <%= f.text_field :name %>
</p>

<p>
    <%= f.label :body %>
    <%= f.text_area :body %>
</p>

<p>

    <%= f.submit %>

</p>

<% end %>

<%= link_to 'Back',articles_path %>

app/views/articles/index.html.erb
<h1>ARTICLES</h1>
<table class = "content">
    <thead>
        <tr>
            <th><h6>ID</h6></th>
            <th><h2>Name</h2></th>
            <th><h2>Body</h2></th>
            <th><h2> </h2></th>
            <th><h2> </h2></th>
            <th><h2> </h2></th>
        </tr>
    </thead>

    <tbody>
        <%# iterate %>
        <%@articles.each do |article| %>
            <tr>
                <%# print %>
                <td id = "article-id"><%= article.id %></td>
                <td id = "article-name"><b><%= article.name %></b></td>
                <td id = "article-body"><%= article.body %></td>
                <td><%= link_to 'Edit', edit_article_path(article.id) %></td>
                <td><%= link_to 'Show',show_article_path(article.id) %></td>
                <td><%= link_to 'Delete', delete_article_path(article.id), data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>
<%= link_to 'Create New Article',new_article_path %>

app/views/articles/new.html.erb
<%# idedeclare kung san pupunta ung action natin %>
<%# equivalent ng html %>
<h1>Create New Article</h1>
<%= form_with scope: :article, url: create_article_path, local: true do |f| %>
<p>
    <% if @article.errors.any? %>
        <ul id = "error_explanation">
            <% @article.errors.full_messages.each do |message| %>
             <li>
                <%= message%>
             </li>
            <% end %>
        </ul>
    <% end %>
</p>

<p>
    <%= f.label :name %>
    <%= f.text_field :name %>
</p>

<p>
    <%= f.label :body %>
    <%= f.text_area :body %>
</p>

<p>

    <%= f.submit %>

</p>

<% end %>

<%= link_to 'Back to Article',articles_path %>

app/views/articles/show.html.erb
<h1><%= @article.name %></h1>
            
<%# print %>
<p class = "content">

    <%= @article.body %>

</p>

<div class = "btn-links">
    <%= link_to 'Edit', edit_article_path(@article.id) %>
    <%= link_to 'Delete', delete_article_path(@article.id), data: { confirm: 'Are you sure?' } %>
    <%= link_to 'Back to Article',articles_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>